/**
 * TRINETRA — Phase 5: Evidence Panel
 * Displays verifiable mathematical evidence generated by specialized analytical models.
 * Principle: "Models generate evidence. The language model explains evidence."
 */

import React from "react"
import { EvidenceItem } from "./EvidenceItem"
import { Binary, ShieldCheck, BarChart3 } from "lucide-react"

interface Props {
  evidence: Record<string, any>
  query?: string
}

export const EvidencePanel: React.FC<Props> = ({ evidence, query }) => {
  if (!evidence || Object.keys(evidence).length === 0) {
    return (
      <div className="p-4 bg-slate-900/40 border border-slate-800 rounded-lg text-center text-xs text-slate-400">
        No mathematical evidence tokens attached to this run.
      </div>
    )
  }

  const regions = evidence.regions || []
  const spectral = evidence.spectral || []
  const crossModal = evidence.cross_modal || []
  const groundings = evidence.groundings || []
  const statistics = evidence.statistics || {}
  const proofs = evidence.metadata?.verification_proofs || []

  return (
    <div className="space-y-3">
      {/* Evidence Banner */}
      <div className="p-2.5 bg-cyan-950/20 border border-cyan-500/30 rounded-lg flex items-start gap-2 text-xs">
        <Binary className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
        <div className="space-y-0.5">
          <p className="text-slate-200 font-semibold leading-tight">
            Verifiable Numerical Evidence
          </p>
          <p className="text-slate-400 text-[11px] leading-relaxed">
            All findings are mathematically bounded by model tensors and verified against consistency gates.
          </p>
        </div>
      </div>

      {/* Aggregate Statistics */}
      {Object.keys(statistics).length > 0 && (
        <div className="p-3 bg-slate-900/70 border border-slate-800 rounded-lg space-y-2">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-300">
            <BarChart3 className="w-3.5 h-3.5 text-emerald-400" />
            <span>Aggregate Spatial Statistics</span>
          </div>
          <div className="grid grid-cols-2 gap-2 text-xs font-mono">
            {Object.entries(statistics).map(([k, v]) => (
              <div key={k} className="p-1.5 bg-slate-800/60 rounded flex flex-col">
                <span className="text-[10px] text-slate-500 uppercase">{k.replace(/_/g, " ")}</span>
                <span className="text-slate-200 font-bold">
                  {typeof v === "number" ? (Number.isInteger(v) ? v.toLocaleString() : v.toFixed(3)) : String(v)}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Regions */}
      {regions.length > 0 && (
        <div className="space-y-1.5">
          <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider font-mono">
            Detected Change Regions ({regions.length})
          </h4>
          <div className="space-y-1.5 max-h-[220px] overflow-y-auto pr-1">
            {regions.map((reg: any, i: number) => (
              <EvidenceItem
                key={reg.region_id || i}
                title={reg.region_id || `Region #${i + 1}`}
                type="region"
                data={{
                  area_hectares: reg.area_hectares,
                  changed_pixels: reg.changed_pixels,
                  confidence: reg.mean_confidence,
                  centroid: reg.centroid_lat ? `${reg.centroid_lat.toFixed(4)}, ${reg.centroid_lon.toFixed(4)}` : undefined,
                }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Cross-Modal Evidence */}
      {crossModal.length > 0 && (
        <div className="space-y-1.5">
          <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider font-mono">
            Cross-Modal Joint Reasoning ({crossModal.length})
          </h4>
          <div className="space-y-1.5">
            {crossModal.map((cm: any, i: number) => (
              <EvidenceItem
                key={cm.cross_modal_id || i}
                title={`Cross-Modal #${i + 1}`}
                type="cross_modal"
                data={{
                  optical_support: cm.optical_support_score,
                  sar_support: cm.sar_support_score,
                  confidence: cm.confidence,
                }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Mathematical Verification Proofs */}
      {proofs.length > 0 && (
        <div className="space-y-1.5">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-emerald-400 font-mono">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Mathematical Gate Proofs ({proofs.length})</span>
          </div>
          <div className="space-y-1 max-h-[160px] overflow-y-auto pr-1">
            {proofs.map((proof: any, i: number) => (
              <div
                key={i}
                className="p-2 bg-emerald-950/20 border border-emerald-500/20 rounded text-[11px] font-mono text-emerald-300/90"
              >
                {proof.check || proof.message || JSON.stringify(proof)}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
