export type AnalysisMode = "single" | "temporal" | "fusion"
export type Confidence = "high" | "medium" | "low"
export type AnalysisStatus = "idle" | "running" | "complete" | "error"
export interface ImageInput { id: string; name: string; size: number; url: string; label: string; modality?: "OPTICAL" | "SAR"; date?: string }
export interface ExecutionStep { label: string; detail: string; duration: string; status: "complete" | "active" | "pending" }
export interface AnalysisRequest { mode: AnalysisMode; images: ImageInput[]; query: string }
export interface GroundingAnnotation { label: string; x: number; y: number; width: number; height: number; color: "cyan" | "amber" }
export interface AnalysisResponse { id: string; mode: AnalysisMode; query: string; answer: string; confidence: Confidence; confidenceScore: number; evidence: string[]; annotations: GroundingAnnotation[]; steps: ExecutionStep[]; model: string; processingTime: string; resolution: string; imageType: string; createdAt: string; images: ImageInput[] }
export const modes: { id: AnalysisMode; label: string; description: string; icon: string }[] = [{ id: "single", label: "Single image", description: "Explore one scene", icon: "◈" }, { id: "temporal", label: "Bi-temporal", description: "Detect change over time", icon: "◌" }, { id: "fusion", label: "Optical + SAR", description: "Fuse complementary sensors", icon: "⌘" }]
export const examples: Record<AnalysisMode, string[]> = { single: ["What land use types are visible in this image?", "Describe the water bodies and vegetation coverage."], temporal: ["What changes are visible between these two dates?", "Show me areas of significant vegetation loss."], fusion: ["Identify flooded regions using combined modality data.", "Compare the optical and radar signatures of this area."] }
export const formatBytes = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`
export const makeImage = (name: string, label: string, modality?: "OPTICAL" | "SAR", date?: string): ImageInput => ({ id: `${name}-${Date.now()}`, name, size: 3200000, url: `/satellite-${modality === "SAR" ? "sar" : "optical"}.svg`, label, modality, date })
export const demoScenarios = [{ id: "urban", title: "Urban growth", mode: "temporal" as const, query: "What changes are visible between these two dates?", response: "The analysis identifies **measurable urban expansion** along the eastern edge of the scene. New built-up surfaces appear as a connected 18% increase, while the central road corridor remains stable. The highlighted evidence regions show where impervious cover replaced mixed vegetation." }, { id: "flood", title: "Flood mapping", mode: "fusion" as const, query: "Identify flooded regions using combined modality data.", response: "Fused optical and SAR evidence suggests **standing water across the southern lowlands**. The radar-dark regions align with low-lying agricultural parcels and are distinct from persistent water bodies. Confidence is medium because cloud cover limits optical confirmation." }, { id: "landuse", title: "Land use scan", mode: "single" as const, query: "What land use types are visible in this image?", response: "The scene is predominantly **agricultural**, with rectangular cultivated parcels, a compact settlement cluster, and a riparian vegetation corridor. A paved road network divides the northern fields from denser development in the southwest." }, { id: "deforestation", title: "Vegetation loss", mode: "temporal" as const, query: "Show me areas of significant vegetation loss.", response: "A concentrated vegetation-loss signature appears in the northwest quadrant. The change region covers approximately 6.4 hectares and has a fragmented edge consistent with clearing activity. Validate against seasonal imagery before operational decisions." }]
export const imagePresets = { optical: makeImage("sentinel-2-north.png", "Optical scene", "OPTICAL", "18 Aug 2025"), sar: makeImage("sentinel-1-radar.png", "Radar scene", "SAR", "18 Aug 2025"), before: makeImage("scene-before.png", "Earlier image", "OPTICAL", "12 Apr 2024"), after: makeImage("scene-after.png", "Later image", "OPTICAL", "18 Aug 2025") }
export const demoRequest = (mode: AnalysisMode, query: string): AnalysisRequest => ({ mode, query, images: mode === "single" ? [imagePresets.optical] : mode === "temporal" ? [imagePresets.before, imagePresets.after] : [imagePresets.optical, imagePresets.sar] })
export const getDemoResult = (request: AnalysisRequest): AnalysisResponse => { const scenario = demoScenarios.find((item) => item.mode === request.mode && item.query.toLowerCase() === request.query.toLowerCase()) ?? demoScenarios.find((item) => item.mode === request.mode) ?? demoScenarios[0]; return { id: `analysis-${Date.now()}`, mode: request.mode, query: request.query, answer: scenario.response, confidence: request.mode === "fusion" ? "medium" : "high", confidenceScore: request.mode === "fusion" ? 0.74 : 0.91, evidence: ["Connected evidence region 01", "Cross-checked spatial pattern", "Compared imagery metadata"], annotations: [{ label: "Primary evidence", x: 18, y: 28, width: 26, height: 22, color: "cyan" }, { label: "Change region", x: 61, y: 42, width: 24, height: 26, color: "amber" }], steps: [{ label: "Images loaded", detail: `${request.images.length} inputs verified`, duration: "0.2s", status: "complete" }, { label: "Imagery aligned", detail: "Normalizing contrast and spatial context", duration: "1.1s", status: "complete" }, { label: "Visual evidence mapped", detail: "Finding regions relevant to your question", duration: "2.4s", status: "complete" }, { label: "Answer composed", detail: "Citing observable evidence", duration: "0.8s", status: "complete" }], model: "SatQuery Vision v0.9", processingTime: "4.5s", resolution: "10 m / pixel", imageType: request.mode === "fusion" ? "Sentinel-2 MSI + Sentinel-1 SAR" : "Sentinel-2 MSI", createdAt: new Date().toISOString(), images: request.images } }
export const analysisAPI = { submitAnalysis: async (request: AnalysisRequest) => { await new Promise((resolve) => setTimeout(resolve, 900)); return getDemoResult(request) } }
export const saveHistory = (item: AnalysisResponse) => { if (typeof window === "undefined") return; const history = JSON.parse(localStorage.getItem("satquery-history") || "[]") as AnalysisResponse[]; localStorage.setItem("satquery-history", JSON.stringify([item, ...history].slice(0, 12))) }
export const loadHistory = (): AnalysisResponse[] => { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem("satquery-history") || "[]") as AnalysisResponse[] } catch { return [] } }
export const confidenceCopy: Record<Confidence, string> = { high: "High confidence — evidence is consistent", medium: "Medium confidence — some aspects are uncertain", low: "Low confidence — verify with a domain expert" }
export const modeRequirements: Record<AnalysisMode, string> = { single: "1 image required", temporal: "2 dated images required", fusion: "Optical + SAR pair required" }
export const modeSlots = (mode: AnalysisMode) => mode === "single" ? [{ label: "Satellite image", hint: "Optical or SAR" }] : mode === "temporal" ? [{ label: "Earlier image", hint: "BEFORE" }, { label: "Later image", hint: "AFTER" }] : [{ label: "Optical image", hint: "OPTICAL" }, { label: "Radar image", hint: "SAR" }]
export const isReady = (mode: AnalysisMode, images: ImageInput[], query: string) => images.length === (mode === "single" ? 1 : 2) && Boolean(query.trim())
export const formatDate = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value))
export const normalizeFile = (file: File, label: string, modality?: "OPTICAL" | "SAR") => ({ id: `${file.name}-${file.lastModified}`, name: file.name, size: file.size, url: URL.createObjectURL(file), label, modality })
export const navItems = [{ href: "/", label: "Overview" }, { href: "/analysis", label: "Workspace" }, { href: "/dashboard", label: "History" }, { href: "/evaluation", label: "Evaluation" }]
export const metricCards = [{ label: "Analyses run", value: "12", delta: "+4 this week" }, { label: "Images processed", value: "27", delta: "3 modalities" }, { label: "Avg. confidence", value: "86%", delta: "Across demo runs" }]
export const evaluationMetrics = [{ label: "Grounding coverage", value: 92, note: "Claims linked to visible regions" }, { label: "Workflow routing", value: 100, note: "Mode selected from user intent" }, { label: "Uncertainty handling", value: 84, note: "Caution shown when evidence is mixed" }]
